// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TestGarageSholomTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testGarageSholom() {
    driver.get("http://127.0.0.1:8000/");
    driver.manage().window().setSize(new Dimension(914, 720));
    driver.findElement(By.linkText("Voir tous les véhicules")).click();
    driver.findElement(By.linkText("Nouveau véhicule")).click();
    driver.findElement(By.id("immatriculation")).click();
    driver.findElement(By.id("immatriculation")).sendKeys("BZ6033RB");
    driver.findElement(By.id("marque")).click();
    driver.findElement(By.id("marque")).sendKeys("TOYOTA");
    driver.findElement(By.id("couleur")).click();
    driver.findElement(By.id("couleur")).sendKeys("Cendre");
    driver.findElement(By.id("modele")).click();
    driver.findElement(By.id("modele")).sendKeys("perferendis");
    driver.findElement(By.id("annee")).sendKeys("2021");
    driver.findElement(By.id("kilometrage")).sendKeys("102395");
    {
      WebElement element = driver.findElement(By.id("kilometrage"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.id("kilometrage"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.id("kilometrage"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.id("kilometrage")).click();
    driver.findElement(By.id("kilometrage")).sendKeys("2036");
    driver.findElement(By.id("carosserie")).click();
    {
      WebElement dropdown = driver.findElement(By.id("carosserie"));
      dropdown.findElement(By.xpath("//option[. = 'Berline']")).click();
    }
    driver.findElement(By.id("energie")).click();
    {
      WebElement dropdown = driver.findElement(By.id("energie"));
      dropdown.findElement(By.xpath("//option[. = 'Essence']")).click();
    }
    driver.findElement(By.id("boite")).click();
    {
      WebElement dropdown = driver.findElement(By.id("boite"));
      dropdown.findElement(By.xpath("//option[. = 'Automatique']")).click();
    }
    driver.findElement(By.cssSelector(".btn-primary")).click();
    driver.findElement(By.cssSelector(".btn-primary")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".btn-primary"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("immatriculation")).click();
    driver.findElement(By.id("immatriculation")).sendKeys("BZ633RB");
    driver.findElement(By.cssSelector(".btn-primary")).click();
    driver.findElement(By.cssSelector(".list-group-item:nth-child(3)")).click();
    driver.findElement(By.linkText("Nouvelle réparation")).click();
    driver.findElement(By.id("vehicule_id")).click();
    driver.findElement(By.id("vehicule_id")).click();
    driver.findElement(By.id("vehicule_id")).click();
    {
      WebElement dropdown = driver.findElement(By.id("vehicule_id"));
      dropdown.findElement(By.xpath("//option[. = 'BZ633RB - TOYOTA perferendis']")).click();
    }
    {
      WebElement dropdown = driver.findElement(By.id("techniciens"));
      dropdown.findElement(By.xpath("//option[. = 'Floy Paucek (Climatisation)']")).click();
    }
    driver.findElement(By.id("duree_main_oeuvre")).click();
    driver.findElement(By.id("duree_main_oeuvre")).click();
    {
      WebElement element = driver.findElement(By.id("duree_main_oeuvre"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("duree_main_oeuvre")).click();
    {
      WebElement dropdown = driver.findElement(By.id("duree_main_oeuvre"));
      dropdown.findElement(By.xpath("//option[. = '2 heures']")).click();
    }
    driver.findElement(By.id("objet_reparation")).click();
    driver.findElement(By.id("objet_reparation")).sendKeys("Complement de gaz");
    driver.findElement(By.cssSelector(".btn-primary")).click();
    driver.findElement(By.cssSelector(".list-group-item:nth-child(4)")).click();
    driver.findElement(By.linkText("Nouveau technicien")).click();
    driver.findElement(By.id("nom")).click();
    driver.findElement(By.id("nom")).sendKeys("GUEKPON");
    driver.findElement(By.id("prenom")).sendKeys("Carleton Bor");
    driver.findElement(By.id("prenom")).click();
    driver.findElement(By.id("prenom")).sendKeys("Carleton Bor G.");
    driver.findElement(By.id("specialite")).click();
    {
      WebElement dropdown = driver.findElement(By.id("specialite"));
      dropdown.findElement(By.xpath("//option[. = 'Électricité auto']")).click();
    }
    driver.findElement(By.cssSelector(".btn-primary")).click();
  }
}
